<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Rsharp_app_release;mzkit_win32;CellaLAB-Desktop</Configurations>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <UseWPF>True</UseWPF>
    <StartupObject>test.Form2</StartupObject>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\console\console.NET5.vbproj" />
    <ProjectReference Include="..\SShClient\SShClient.vbproj" />
  </ItemGroup>
</Project>